site_name: pyquaternion 
site_description: A fully featured python module for quaternion representation, manipulation, 3D rotation and animation.
site_author: Kieran Wynn
repo_url: https://github.com/KieranWynn/pyquaternion
site_url: http://kieranwynn.github.io/pyquaternion/
theme: readthedocs
